### PR TITLE
Fix IJBC evaluating issue in IJB_evals.py by replacing np.loadtxt with pd.read_csv

### PR DESCRIPTION
**Pull request by leondgarse**
Fix [IJBC evaluating issue](https://github.com/deepinsight/insightface/pull/1349#issuecomment-748953774) by using `pd.read_csv` instead of `np.loadtxt`. Tested scenarios: `IJBB` / `IJBC` in `11` / `1N`.
- `IJBC` `11` result

|                                                 |    1e-06 |    1e-05 |   0.0001 |    0.001 |     0.01 |      0.1 |
|:------------------------------------------------|---------:|---------:|---------:|---------:|---------:|---------:|
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N1D1F1 | 0.882855 | 0.940021 | 0.96073  | 0.974638 | 0.983331 | 0.991001 |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N1D1F0 | 0.87948  | 0.938692 | 0.959145 | 0.973104 | 0.982359 | 0.990387 |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N1D0F1 | 0.86409  | 0.933016 | 0.958122 | 0.973207 | 0.982666 | 0.990643 |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N1D0F0 | 0.862453 | 0.931482 | 0.956486 | 0.971979 | 0.981848 | 0.99008  |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N0D1F1 | 0.898451 | 0.944726 | 0.962775 | 0.975252 | 0.983638 | 0.990796 |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N0D1F0 | 0.894258 | 0.9413   | 0.961037 | 0.973462 | 0.982922 | 0.99054  |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N0D0F1 | 0.885719 | 0.942936 | 0.962162 | 0.975098 | 0.983484 | 0.990796 |
| IJB_result/MS1MV2-ResNet100-Arcface_IJBC_N0D0F0 | 0.890627 | 0.939357 | 0.96027  | 0.973104 | 0.982922 | 0.990387 |

- `IJBC` `1N` result
```py
top1: 0.963865, top5: 0.975399, top10: 0.978717
far = 0.0100000000 pr = 0.9996427295 th = -0.1018287803
far = 0.1000000000 pr = 0.9907109682 th = 0.1000848608
```

### CODE REVIEW

**Comment by pansanity666** [comment]
The 1:N results for `MS1MV2-ResNet100-Arcface` from `IJB_1N.py` is :
far = 0.0100000000 pr = 0.9293625274 th = 0.4612037852
far = 0.1000000000 pr = 0.9536569183 th = 0.3745640939

Maybe there still exist problems for the 1:N part in your `IJB_evals.py` LOL

**Comment by pansanity666** [comment]
> The 1:N results for `MS1MV2-ResNet100-Arcface` from `IJB_1N.py` is :
> top1 = 0.9638646455366713
> top5 = 0.9753993773286378
> top10 = 0.9787168886847344
> far = 0.0100000000 pr = 0.9293625274 th = 0.4612037852
> far = 0.1000000000 pr = 0.9536569183 th = 0.3745640939
> 
> The top 1-10 is right, but pr and th is wrong. Maybe there still exist problems for the 1:N part in your `IJB_evals.py` LOL

I have found the problem. In line 312, `neg_sims` should be `neg_sims_sorted`.

**Comment by nttstar** [comment]
@leondgarse Can you help check @pansanity666 's problem?

**Comment by leondgarse** [comment]
@pansanity666 Yes, you are right! I just renamed the previous `neg_sims` to `neg_sims_sorted`, and forgot the following one, sorry for my fault...
Result after this fix:
```py
far = 0.0100000000 pr = 0.9293625274 th = 0.4612039876
far = 0.1000000000 pr = 0.9536569183 th = 0.3745641067
```
Seems better.

**Comment by nttstar** [comment]
@leondgarse Thanks!

**Comment by pansanity666** [comment]
> @pansanity666 Yes, you are right! I just renamed the previous `neg_sims` to `neg_sims_sorted`, and forgot the following one, sorry for my fault...
> Result after this fix:
> 
> ```python
> far = 0.0100000000 pr = 0.9293625274 th = 0.4612039876
> far = 0.1000000000 pr = 0.9536569183 th = 0.3745641067
> ```
> 
> Seems better.

So do you know where to find the code for the calculation of DIR(TPIR)-FAR(FPIR) curve (which are commonly used in many papers) for IJB-C?  It seems that the codes in this project are not for DIR-FAR curve?  Could you help me please? @leondgarse @nttstar

**Comment by leondgarse** [comment]
I think maybe we can do it like this, but not sure if it's right or not.
- After calculated `similarity` and both `pos_sims` and `neg_sims` in `evaluation_1N`, do plot using:
```py
score = np.concatenate([pos_sims, neg_sims])
label = np.concatenate([np.ones_like(pos_sims),np.zeros_like(neg_sims)])
IJB_evals.plot_roc_and_calculate_tpr(scores=[score], names=['aa'], label=label)
```
- Result
```py
top1: 0.940896, top5: 0.962804, top10: 0.968062
pos_sims: (10270,), neg_sims: (18937880,), neg_sims_sorted: 1027
far = 0.0100000000 pr = 0.8148977605 th = 0.5481127858
far = 0.1000000000 pr = 0.9211295034 th = 0.3917333633
```

|    |    1e-06 |    1e-05 |   0.0001 |    0.001 |     0.01 |      0.1 |
|:---|---------:|---------:|---------:|---------:|---------:|---------:|
| aa | 0.391918 | 0.877799 | 0.929503 | 0.953944 | 0.972055 | 0.985784 |

Figure_2

- Comparing `1:1` roc curve

|    |    1e-06 |    1e-05 |   0.0001 |    0.001 |     0.01 |      0.1 |
|:---|---------:|---------:|---------:|---------:|---------:|---------:|
| aa | 0.352678 | 0.881694 | 0.928724 | 0.954041 | 0.972055 | 0.985784 |

ghostnet_11

**Comment by pansanity666** [comment]
> I think maybe we can do it like this, but not sure if it's right or not.
> 
> * After calculated `similarity` and both `pos_sims` and `neg_sims` in `evaluation_1N`, do plot using:
> 
> ```python
> score = np.concatenate([pos_sims, neg_sims])
> label = np.concatenate([np.ones_like(pos_sims),np.zeros_like(neg_sims)])
> IJB_evals.plot_roc_and_calculate_tpr(scores=[score], names=['aa'], label=label)
> ```
> 
> * Result
> 
> ```python
> top1: 0.940896, top5: 0.962804, top10: 0.968062
> pos_sims: (10270,), neg_sims: (18937880,), neg_sims_sorted: 1027
> far = 0.0100000000 pr = 0.8148977605 th = 0.5481127858
> far = 0.1000000000 pr = 0.9211295034 th = 0.3917333633
> ```
> 
> 1e-06	1e-05	0.0001	0.001	0.01	0.1
> aa	0.391918	0.877799	0.929503	0.953944	0.972055	0.985784
> Figure_2
> 
> * Comparing `1:1` roc curve
> 
> 1e-06	1e-05	0.0001	0.001	0.01	0.1
> aa	0.352678	0.881694	0.928724	0.954041	0.972055	0.985784
> ghostnet_11

Thank you~, In fact, I am questioning that the chosen of pos_sim and neg_sim is not the same as the definition of TPIR@FPIR, which is the commonly used protocols for open-set face identification, and can be find [here](https://www.researchgate.net/publication/235709405_Handbook_of_Face_Recognition_the_second_edition). I have re-written the code based on the definition of TPIR and FPIR, thank you very much!

**Comment by leondgarse** [comment]
OK, as I'm still learning what those abbreviated words stand for. LOL
I tried using `bob.measure.detection_identification_rate` in [bob.measure](https://pythonhosted.org/bob/temp/bob.measure/doc/guide.html#overview) to calculate`DIR` value.

In `MS1MV2-ResNet100-Arcface` case:
```py
# In `evaluation_1N`
Fars = [0.001, 0.01, 0.1, 0.2, 0.3]
...
cmc_score = list(zip(neg_sims.reshape(pos_sims.shape[0], -1), np.expand_dims(pos_sims, -1)))
for far, pos in zip(Fars, required_topk):
    th = neg_sims_sorted[pos - 1]
    recall = np.sum(pos_sims > th) / query_num
    dir = bob.measure.detection_identification_rate(cmc_score, threshold=th, rank=1)
    print("far = {:.10f} pr = {:.10f} th = {:.10f} dir = {:.10f}".format(far, recall, th, dir))

# query_feats: (19593, 512), gallery_feats: (3531, 512)
# similarity shape: (19593, 3531)
# top_inds shape: (19593, 3531)
# top1: 0.963865, top5: 0.975399, top10: 0.978717
# pos_sims: (19593,), neg_sims: (69163290,), neg_sims_sorted: 5878
# far = 0.0010000000 pr = 0.7161231052 th = 0.6986301622 dir = 0.7160210279
# far = 0.0100000000 pr = 0.9293625274 th = 0.4612039876 dir = 0.9286990252
# far = 0.1000000000 pr = 0.9536569183 th = 0.3745641067 dir = 0.9516153728
# far = 0.2000000000 pr = 0.9588118205 th = 0.3504652539 dir = 0.9559026183
# far = 0.3000000000 pr = 0.9619762160 th = 0.3363156216 dir = 0.9585055887

bob.measure.detection_identification_rate(aa, threshold=0, rank=1)
# 0.9638646455366713
bob.measure.detection_identification_rate(aa, threshold=0, rank=10)
# 0.9787168886847344
```
It's this seems like the result you are looking for?

**Comment by leondgarse** [comment]
I have an issue on this `1N` calculation too...
- In my understanding, `FAR` is defined the `False Acceptance Rate`, which should be the `number of false accepted negatives` / `total number of negatives`.
- In the `IJB_1N.py` evaluation, we are using
  ```py
  Fars = [0.01, 0.1]
  required_topk = [math.ceil(query_num * x) for x in Fars]
  for far, pos in zip(Fars, required_topk):
      th = neg_sims[pos - 1]
  ```
  I think this is calculating `FAR` using `total number of positives`, which is `query_num`, and then selecting `thresh` in `neg_sims`. Why is this?
  IMO, the `query_num` above should be `neg_sims.shape[0]`:
  ```py
  Fars = [0.01, 0.1]
  required_topk = [math.ceil(neg_sims.shape[0] * x) for x in Fars]
  for far, pos in zip(Fars, required_topk):
      th = neg_sims[pos - 1]
  ```
- Result
  ```py
  # Using `query_num`
  far = 0.0010000000 pr = 0.7161231052 th = 0.6986301622
  far = 0.0100000000 pr = 0.9293625274 th = 0.4612039876

  # Using `neg_sims.shape[0]`
  far = 0.0100000000 pr = 0.9837697137 thresh = 0.1792629114
  far = 0.1000000000 pr = 0.9908640841 thresh = 0.0950367928
  ```
  This is also matching the result using [bob.measure.far_threshold](https://pythonhosted.org/bob/temp/bob.measure/doc/guide.html#verification):
  ```py
  bob.measure.far_threshold(neg_sims_sorted, [], far_value=0.01, is_sorted=True)
  # 0.17926293508125518
  bob.measure.far_threshold(neg_sims_sorted, [], far_value=0.1, is_sorted=True)
  # 0.09503679281968891
  ```

And @pansanity666 , I also ploted the **DIR-FAR** curve using `bob.measure.plot.detection_identification_curve`, but it actually needs negative values of `non-gallery` items to calculate `FAR` values, which I don't known where to find them, so I'm using the total negatives here:
```py
neg_sims = neg_sims.reshape(pos_sims.shape[0], -1)
cmc_scores = list(zip(neg_sims, np.expand_dims(pos_sims, -1)))
cmc_scores_none = list(zip(neg_sims, [None] * pos_sims.shape[0]))
bob.measure.plot.detection_identification_curve(cmc_scores + cmc_scores_none, rank=1, logx=True)

plt.xlabel('False Alarm Rate')
plt.xlim([0.0001, 1])
plt.ylabel('Detection & Identification Rate (%)')
plt.ylim([0,1])
plt.grid()
plt.tight_layout()
```
dir_far

**Comment by pansanity666** [comment]
> I have an issue on this `1N` calculation too...
> 
> * In my understanding, `FAR` is defined the `False Acceptance Rate`, which should be the `number of false accepted negatives` / `total number of negatives`.
> * In the `IJB_1N.py` evaluation, we are using
>   ```python
>   Fars = [0.01, 0.1]
>   required_topk = [math.ceil(query_num * x) for x in Fars]
>   for far, pos in zip(Fars, required_topk):
>       th = neg_sims[pos - 1]
>   ```
>   
>   
>   I think this is calculating `FAR` using `total number of positives`, which is `query_num`, and then selecting `thresh` in `neg_sims`. Why is this?
>   IMO, the `query_num` above should be `neg_sims.shape[0]`:
>   ```python
>   Fars = [0.01, 0.1]
>   required_topk = [math.ceil(neg_sims.shape[0] * x) for x in Fars]
>   for far, pos in zip(Fars, required_topk):
>       th = neg_sims[pos - 1]
>   ```
> * Result
>   ```python
>   # Using `query_num`
>   far = 0.0010000000 pr = 0.7161231052 th = 0.6986301622
>   far = 0.0100000000 pr = 0.9293625274 th = 0.4612039876
>   
>   # Using `neg_sims.shape[0]`
>   far = 0.0100000000 pr = 0.9837697137 thresh = 0.1792629114
>   far = 0.1000000000 pr = 0.9908640841 thresh = 0.0950367928
>   ```
>   
>   
>   This is also matching the result using [bob.measure.far_threshold](https://pythonhosted.org/bob/temp/bob.measure/doc/guide.html#verification):
>   ```python
>   bob.measure.far_threshold(neg_sims_sorted, [], far_value=0.01, is_sorted=True)
>   # 0.17926293508125518
>   bob.measure.far_threshold(neg_sims_sorted, [], far_value=0.1, is_sorted=True)
>   # 0.09503679281968891
>   ```
> 
> And @pansanity666 , I also ploted the **DIR-FAR** curve using `bob.measure.plot.detection_identification_curve`, but it actually needs negative values of `non-gallery` items to calculate `FAR` values, which I don't known where to find them, so I'm using the total negatives here:
> 
> ```python
> neg_sims = neg_sims.reshape(pos_sims.shape[0], -1)
> cmc_scores = list(zip(neg_sims, np.expand_dims(pos_sims, -1)))
> cmc_scores_none = list(zip(neg_sims, [None] * pos_sims.shape[0]))
> bob.measure.plot.detection_identification_curve(cmc_scores + cmc_scores_none, rank=1, logx=True)
> 
> plt.xlabel('False Alarm Rate')
> plt.xlim([0.0001, 1])
> plt.ylabel('Detection & Identification Rate (%)')
> plt.ylim([0,1])
> plt.grid()
> plt.tight_layout()
> ```
> 
> dir_far

As to the origin paper for IJB-C, there are two disjoint gallery, i.e., G1 and G2. The ids in them are disjoint with each other. The probe_mixed contains ids from both G1 and G2. In my understanding, The proper way to conduct open-set 1:N for IJB-C is :
calculate metics for probe-G1, calculate  metics for probe-G2, and then average them.

**Comment by leondgarse** [comment]
@pansanity666 Great! I have updated a separated gallery version in [my own fork IJB_evals.py](https://github.com/leondgarse/insightface/blob/bc4404c2fa68e7e76e7ccaa49df435478f6023df/evaluation/IJB/IJB_evals.py#L296), and it's using `neg_sims.shape[0]` instead of `query_num` calculating `FAR`, but not the `non_gallery_sims`.
- Result gathering galleries together:
```sh
$ CUDA_VISIBLE_DEVICES='1' IJB_evals.py -R IJB_result/MS1MV2-ResNet100-Arcface_IJBC.npz -d /datasets/IJB_release/ -s IJBC -N 
>>>> Reload from backup: /datasets/IJB_release/IJBC_backup.npz ...
>>>> Reload embeddings from: IJB_result/MS1MV2-ResNet100-Arcface_IJBC.npz
>>>> Done.
>>>> Reload from backup: /datasets/IJB_release/IJBC_gallery_prob_backup.npz ...
Extract template feature: 100%|████████████████████| 1772/1772 [00:00<00:00, 4045.26it/s]
Extract template feature: 100%|████████████████████| 1759/1759 [00:00<00:00, 4058.93it/s]
Extract template feature: 100%|████████████████████| 19593/19593 [00:05<00:00, 3588.77it/s]
g1_templates_feature: (1772, 512)
g2_templates_feature: (1759, 512)
probe_mixed_templates_feature: (19593, 512)
probe_mixed_unique_subject_ids: (19593,)
query_feats: (19593, 512), gallery_feats: (3531, 512)
pos_sims: (19593,), neg_sims: (19593, 3530), non_gallery_sims: 0
top1: 0.963865, top5: 0.975399, top10: 0.978717
far = 0.0100000000 pr = 0.9837697137 thresh = 0.1792629114
far = 0.1000000000 pr = 0.9908640841 thresh = 0.0950367928
```
- Result separating galleries [g1, g2]:
```sh
$ CUDA_VISIBLE_DEVICES='1' IJB_evals.py -R IJB_result/MS1MV2-ResNet100-Arcface_IJBC.npz -d /datasets/IJB_release/ -s IJBC -N -S
>>>> Reload from backup: /datasets/IJB_release/IJBC_backup.npz ...
>>>> Reload embeddings from: IJB_result/MS1MV2-ResNet100-Arcface_IJBC.npz
>>>> Done.
>>>> Reload from backup: /datasets/IJB_release/IJBC_gallery_prob_backup.npz ...
Extract template feature: 100%|████████████████████| 1772/1772 [00:00<00:00, 4082.68it/s]
Extract template feature: 100%|████████████████████| 1759/1759 [00:00<00:00, 4173.97it/s]
Extract template feature: 100%|████████████████████| 19593/19593 [00:05<00:00, 3576.20it/s]
g1_templates_feature: (1772, 512)
g2_templates_feature: (1759, 512)
probe_mixed_templates_feature: (19593, 512)
probe_mixed_unique_subject_ids: (19593,)
>>>> Gallery 1
query_feats: (19593, 512), gallery_feats: (1772, 512)
pos_sims: (9670,), neg_sims: (9670, 1771), non_gallery_sims: 9923
top1: 0.975698, top5: 0.983351, top10: 0.985212
far = 0.0100000000 pr = 0.9867631851 thresh = 0.1801450617
far = 0.1000000000 pr = 0.9916235781 thresh = 0.0954084478
>>>> Gallery 2
query_feats: (19593, 512), gallery_feats: (1759, 512)
pos_sims: (9923,), neg_sims: (9923, 1758), non_gallery_sims: 9670
top1: 0.958581, top5: 0.972186, top10: 0.976418
far = 0.0100000000 pr = 0.9805502368 thresh = 0.1819719129
far = 0.1000000000 pr = 0.9899224025 thresh = 0.0961066088
>>>> Mean
[Mean] top1: 0.967029, top5: 0.977696, top10: 0.980758
[Mean] far = 0.0100000000 pr = 0.9836567110
[Mean] far = 0.1000000000 pr = 0.9907729903
```
dir_far_sep

**Comment by leondgarse** [comment]
I finally figured out the usage of the `non_gallery` items, and made a pull request. There are actually multiple issues in the previous implementation...

**Pull request merged**
