### PR TITLE
Gradio Web Demo

### PR DESCRIPTION
**Pull request by AK391**
easy to use web demo using gradio on huggingface spaces

### CODE REVIEW

**Comment by AK391** [comment]
@nttstar

**Comment by nttstar** [comment]
@AK391 Thanks! I will put it in examples.

**Comment by AK391** [comment]
@nttstar great thanks, I have one example there for mona lisa, let me know if you want to add more

**Comment by nttstar** [comment]
Yes, maybe https://github.com/deepinsight/insightface/blob/master/python-package/insightface/data/images/t1.jpg

**Comment by nttstar** [comment]
BTW: Is 1:1 verification achievable by gradio?

**Comment by AK391** [comment]
> Yes, maybe https://github.com/deepinsight/insightface/blob/master/python-package/insightface/data/images/t1.jpg

I have added this image to the demo

**Comment by AK391** [comment]
> BTW: Is 1:1 verification achievable by gradio?

yes it should be, do you have a example?

**Comment by nttstar** [comment]
@AK391 Sorry for the late reply. Any pair will be ok, such as obama_1 vs obama_2.

**Comment by AK391** [comment]
@nttstar added a web demo link for SCRFD

**Comment by nttstar** [comment]
Hello @AK391 , I added this link to the SCRFD page: https://github.com/deepinsight/insightface/tree/master/detection/scrfd

**Comment by AK391** [comment]
@nttstar thanks

**Pull request closed without merging**
