### PR TITLE
Fix IJB 1:N evaluation in IJB_evals.py

### PR DESCRIPTION
**Pull request by leondgarse**
For Issue [calculating 1:N DIR-FAR in IJB evaluation](https://github.com/deepinsight/insightface/pull/1364#issuecomment-757717175).

- In my understanding and according to the discussion:
  - In `1:N` evaluation, `gallery 1` and `gallery 2` should be calculated separately, as calculating `FAR` needs the `non_gallery` distances.
  - `FAR` is defined the `False Acceptance Rate`, which should be the `number of false accepted negatives / total number of negatives`. Currently we are using `query_num`, which is the `total number of positives`, and then selecting thresh in `neg_sims`. I think this is not right...
  - In this fix, I'm using `gallery 2` data as `non_gallery` items in `gallery 1` and calculating `FAR`, and `gallery 1` for `gallery 2`. Then calculating mean value of `TPIR` on these two galleries.
  - The `non_gallery` distance should NOT be flattened, It's actually using the max value in each query to calculate `FAR` thresh...
  - `TPIR` value, which is `recall` in code, should have another condition, that the positive distance should be larger than the max negative distance in a single query.
    ```py
    correct_pos_cond = pos_sims > neg_sims.max(1)
    ```
- This is also matching the result using `bob.measure.far_threshold` and `bob.measure.detection_identification_rate`. The plotted curve matching `bob.measure.plot.detection_identification_curve`.

- Result using `MS1MV2-ResNet100-Arcface` on `IJBC`:
  ```py
  # Before fix
  top1: 0.963865, top5: 0.975399, top10: 0.978717
  far = 0.0010000000 pr = 0.7161231052 th = 0.6986301622
  far = 0.0100000000 pr = 0.9293625274 th = 0.4612039876
  far = 0.1000000000 pr = 0.9536569183 th = 0.3745641067
  ```
  ```py
  # After fix
  $ CUDA_VISIBLE_DEVICES='1' ./IJB_evals.py -R IJB_result/MS1MV2-ResNet100-Arcface_IJBC.npz -d /datasets/IJB_release/ -s IJBC -N
  >>>> Reload from backup: /datasets/IJB_release/IJBC_backup.npz ...
  >>>> Reload embeddings from: IJB_result/MS1MV2-ResNet100-Arcface_IJBC.npz
  >>>> Done.
  >>>> Reload from backup: /datasets/IJB_release/IJBC_gallery_prob_backup.npz ...
  Extract template feature: 100%|███████████████████| 1772/1772 [00:00<00:00, 3969.74it/s]
  Extract template feature: 100%|███████████████████| 1759/1759 [00:00<00:00, 3977.01it/s]
  Extract template feature: 100%|███████████████████| 19593/19593 [00:05<00:00, 3404.46it/s]
  g1_templates_feature: (1772, 512)
  g2_templates_feature: (1759, 512)
  probe_mixed_templates_feature: (19593, 512)
  probe_mixed_unique_subject_ids: (19593,)
  >>>> Gallery 1
  query_feats: (19593, 512), gallery_feats: (1772, 512)
  pos_sims: (9670,), neg_sims: (9670, 1771), non_gallery_sims: (9923, 1772)
  top1: 0.975698, top5: 0.983351, top10: 0.985212
  >>>> Gallery 2
  query_feats: (19593, 512), gallery_feats: (1759, 512)
  pos_sims: (9923,), neg_sims: (9923, 1758), non_gallery_sims: (9670, 1759)
  top1: 0.958581, top5: 0.972186, top10: 0.976418
  >>>> Mean
  [Mean] top1: 0.967029, top5: 0.977696, top10: 0.980758
  ```

  |    far |   g1_tpir |   g1_thresh |   g2_tpir |   g2_thresh |   mean_tpir |
  |-------:|----------:|------------:|----------:|------------:|------------:|
  | 0.0001 |  0.359359 |    0.841509 |  0.808626 |    0.615563 |    0.583993 |
  | 0.001  |  0.824405 |    0.639982 |  0.876348 |    0.537679 |    0.850377 |
  | 0.01   |  0.954188 |    0.412905 |  0.929356 |    0.419757 |    0.941772 |
  | 0.1    |  0.969183 |    0.338687 |  0.949612 |    0.338081 |    0.959398 |
  | 1      |  0.975698 |    0.185379 |  0.958581 |    0.190272 |    0.96714  |

- Plotted curve of `DIR@FAR` and calculated `auc` value:
  r100_ijbc_dir_far_2
- Using `thresh = non_gallery_sims_sorted[max(int((non_gallery_sims_sorted.shape[0]) * far) - 1, 0)]` instead of `thresh = non_gallery_sims_sorted[int(np.ceil(non_gallery_sims_sorted.shape[0] * far)) - 1]` can match exactly the result of using `bob.measure.plot.detection_identification_curve`
  r100_ijbc_dir_far_comparing_bob

- Plot multi by using `--plot_only`:
  ```sh
  $ ./IJB_evals.py -P IJB_result/glint360k_r100FC_1.0_fp16_cosface8GPU_IJBC.npz IJB_result/MS1MV2-ResNet100-Arcface_IJBC.npz -N
  ```
glint_r100_ijbc_dir_far

### CODE REVIEW

**Comment by nttstar** [comment]
@leondgarse Hi does this issue been fixed?

**Comment by leondgarse** [comment]
I think my calculation is right, by comparing the result with `bob.measure`. Besides, I'm using this `IJB_evals.py` in my own [Keras_insightface](https://github.com/leondgarse/Keras_insightface).
Just this PR has been too long ago, and your project architecture has changed a lot since then. You know, the full `evalution` folder is gone... Thus I may close this.

**Comment by nttstar** [comment]
@leondgarse Thanks! Any new PR is welcome!

**Comment by nttstar** [comment]
Now it's in https://github.com/deepinsight/insightface/tree/master/recognition/_evaluation_/ijb

**Pull request closed without merging**
