### PR TITLE
Reformat and speed up IJB evaluation

### PR DESCRIPTION
**Pull request by leondgarse**
Add a whole new `IJB_evals.py`. It's actually used in my project [leondgarse/Keras_insightface](https://github.com/leondgarse/Keras_insightface).  Though there still are lots of issues, I'm also applying to add in the readme, if it's convenience for you.
### Summary changes
- The main functional change is using batched images for extracting embeddings, which will speed up this evaluation. In my test, it can finish `IJBB` all 8 testing `N{0,1}D{0,1}F{0,1}` scenarios in `~23 mins`.
- Then gather `IJB_11.py` / `IJB_1N.py` / `embedding.py` together, as most functions are common for `11` / `1N`.
- Most functions are changed in format and printing information. but their basic logic is similar.
- The meaning of `use_norm_score` confused me, as normalization is applied when it's `False`. I implemented the opposite way, so my `N0` means the original `N1`. 
- Replace all `read_xxx` functions with one `read_IJB_meta_columns_to_int`.
- Use `tqdm` as process bar.
- Other `saving` / `restore` / `plot_only` functions.

### Basic usage
- In the case placing `IJB` dataset `/media/SD/IJB_release`, basic usage will be:
```sh
# Test mxnet model, default scenario N0D1F1
CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m '/media/SD/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model,0' -d /media/SD/IJB_release -L

# Test keras h5 model, default scenario N0D1F1
CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m 'checkpoints/basic_model.h5' -d /media/SD/IJB_release -L

# `-B` to run all 8 tests N{0,1}D{0,1}F{0,1}
CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m '/media/SD/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model,0' -d /media/SD/IJB_release -B -L

# `-N` to run 1N test
CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m '/media/SD/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model,0' -d /media/SD/IJB_release -N -L

# `-E` to save embeddings data
CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m '/media/SD/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model,0' -d /media/SD/IJB_release -E
# Then can be restored for other tests, add `-E` to save again
python IJB_evals.py -R IJB_result/MS1MV2-ResNet100-Arcface_IJBB.npz -d /media/SD/IJB_release -B

# Plot result only, this needs the `label` data, which can be saved using `-L` parameter.
# Or should provide the label txt file.
python IJB_evals.py --plot_only /media/SD/IJB_release/IJBB/result/*100*.npy /media/SD/IJB_release/IJBB/meta/ijbb_template_pair_label.txt
```
### Run time
- Do all 8 tests `N{0,1}D{0,1}F{0,1}` on `IJBB`, using `batch_size=64`
```sh
$ time CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m '/media/SD/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model,0' -d /media/SD/IJB_release -b 64 -B -F -L
#  real    23m36.871s
#  user    68m56.171s
#  sys     138m6.504s
```
### Help info
```sh
usage: IJB_evals.py [-h] [-m MODEL_FILE] [-d DATA_PATH] [-s SUBSET]
                    [-b BATCH_SIZE] [-R SAVE_RESULT] [-L] [-E] [-B] [-N] [-F]
                    [-p [PLOT_ONLY [PLOT_ONLY ...]]]

optional arguments:
  -h, --help            show this help message and exit
  -m MODEL_FILE, --model_file MODEL_FILE
                        Saved model file path, could be keras / mxnet one
                        (default: None)
  -d DATA_PATH, --data_path DATA_PATH
                        Dataset path (default: ./)
  -s SUBSET, --subset SUBSET
                        Subset test target, could be IJBB / IJBC (default:
                        IJBB)
  -b BATCH_SIZE, --batch_size BATCH_SIZE
                        Batch size for get_embeddings (default: 64)
  -R SAVE_RESULT, --save_result SAVE_RESULT
                        Filename for saving / restore result (default:
                        IJB_result/{model_name}_{subset}.npz)
  -L, --save_label      Save label data, useful for plot only (default: False)
  -E, --save_embeddings
                        Save embeddings data (default: False)
  -B, --is_bunch        Run all 8 tests N{0,1}D{0,1}F{0,1} (default: False)
  -N, --is_one_2_N      Run 1:N test instead of 1:1 (default: False)
  -F, --force_reload    Force reload, instead of using cache (default: False)
  -p [PLOT_ONLY [PLOT_ONLY ...]], --plot_only [PLOT_ONLY [PLOT_ONLY ...]]
                        Plot saved results, Format 1 2 3 or 1, 2, 3 or *.npy
                        (default: None)
```
### Test printed log
```sh
$ time CUDA_VISIBLE_DEVICES='1' python IJB_evals.py \
        -m '/media/SD/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model,0' \
        -d /media/SD/IJB_release -b 64 -B -F -L -E
  >>>> loading mxnet model: /media/SD/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model 0 [gpu(0)]
  [09:17:15] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
  [09:17:15] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
  >>>> Loading templates and medias...
  templates: (227630,), medias: (227630,), unique templates: (12115,)
  >>>> Loading pairs...
  p1: (8010270,), unique p1: (1845,)
  p2: (8010270,), unique p2: (10270,)
  label: (8010270,), label value counts: {0: 8000000, 1: 10270}
  >>>> Loading images...
  img_names: (227630,), landmarks: (227630, 5, 2), face_scores: (227630,)
  face_scores value counts: {0.1: 2515, 0.2: 0, 0.3: 62, 0.4: 94, 0.5: 136, 0.6: 197, 0.7: 291, 0.8: 538, 0.9: 223797}
  >>>> Saving backup to: /media/SD/IJB_release/IJBB_backup.npz ...

  Embedding: 100%|█████████████████████████████████████████████████████████| 3557/3557 [17:00<00:00,  3.48it/s]
  >>>> N1D1F1 True True True
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 4948.45it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:39<00:00,  2.04it/s]
  >>>> N1D1F0 True True False
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 5010.94it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:38<00:00,  2.12it/s]
  >>>> N1D0F1 True False True
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 5018.59it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:38<00:00,  2.12it/s]
  >>>> N1D0F0 True False False
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 4994.06it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:38<00:00,  2.13it/s]
  >>>> N0D1F1 False True True
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 4984.76it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:38<00:00,  2.12it/s]
  >>>> N0D1F0 False True False
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 4997.04it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:38<00:00,  2.12it/s]
  >>>> N0D0F1 False False True
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 4992.75it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:38<00:00,  2.12it/s]
  >>>> N0D0F0 False False False
  Extract template feature: 100%|██████████████████████████████████████| 12115/12115 [00:02<00:00, 5007.00it/s]
  Verification: 100%|██████████████████████████████████████████████████████████| 81/81 [00:38<00:00,  2.12it/s]
  |                                      |    1e-06 |    1e-05 |   0.0001 |    0.001 |     0.01 |      0.1 |
  |:-------------------------------------|---------:|---------:|---------:|---------:|---------:|---------:|
  | MS1MV2-ResNet100-Arcface_IJBB_N1D1F1 | 0.408861 | 0.899513 | 0.946349 | 0.964167 | 0.976144 | 0.98666  |
  | MS1MV2-ResNet100-Arcface_IJBB_N1D1F0 | 0.389192 | 0.898442 | 0.94557  | 0.96261  | 0.975268 | 0.986076 |
  | MS1MV2-ResNet100-Arcface_IJBB_N1D0F1 | 0.402142 | 0.893184 | 0.943622 | 0.963096 | 0.975755 | 0.986173 |
  | MS1MV2-ResNet100-Arcface_IJBB_N1D0F0 | 0.382765 | 0.893281 | 0.942454 | 0.961538 | 0.975073 | 0.985589 |
  | MS1MV2-ResNet100-Arcface_IJBB_N0D1F1 | 0.42814  | 0.908179 | 0.948978 | 0.964654 | 0.976728 | 0.986563 |
  | MS1MV2-ResNet100-Arcface_IJBB_N0D1F0 | 0.392989 | 0.903895 | 0.947614 | 0.962999 | 0.975755 | 0.986076 |
  | MS1MV2-ResNet100-Arcface_IJBB_N0D0F1 | 0.425998 | 0.907011 | 0.947809 | 0.96446  | 0.976436 | 0.986563 |
  | MS1MV2-ResNet100-Arcface_IJBB_N0D0F0 | 0.389971 | 0.904187 | 0.946738 | 0.962025 | 0.976144 | 0.985979 |
```
 - Restore embeddings to do `1N`.
```sh
$ python IJB_evals.py -R IJB_result/MS1MV2-ResNet100-Arcface_IJBB.npz -d /media/SD/IJB_release/ -N
>>>> Reloading from backup: /media/SD/IJB_release/IJBB_backup.npz ...
>>>> Reload embeddings from: IJB_result/MS1MV2-ResNet100-Arcface_IJBB.npz
>>>> Reloading from backup: /media/SD/IJB_release/IJBB_gallery_prob_backup.npz ...
Extract template feature: 100%|███████████████████████████████████████| 1845/1845 [00:00<00:00, 6910.71it/s]
gallery_templates_feature: (1845, 512)
gallery_unique_subject_ids: (1845,)
Extract template feature: 100%|███████████████████████████████████████| 10270/10270 [00:01<00:00, 5729.43it/s]
probe_mixed_templates_feature: (10270, 512)
probe_mixed_unique_subject_ids: (10270,)
query_feats: (10270, 512), gallery_feats: (1845, 512)
similarity shape: (10270, 1845)
top_inds shape: (10270, 1845)
top1: 0.951412, top5: 0.968841, top10: 0.973223
pos_sims: (10270,), neg_sims: (18937880,), neg_sims_sorted: 1027
far = 0.0100000000 pr = 0.9998052580 th = -0.1273625240
far = 0.1000000000 pr = 0.9995131451 th = -0.0905822399
```

### CODE REVIEW

**Comment by pansanity666** [comment]
Hi, my evaluation result on IJBB is right, but the one for IJBC is abnormally poor.

**Comment by pansanity666** [comment]
Hi, my evaluation result on IJBB is right, but the one for IJBC is abnormally poor.

**Comment by pansanity666** [comment]
Hi, my 1:1 verification result on IJBB is right, but the one for IJBC is abnormally poor. 
The result for IJBB is close to the results reported in the paper.
While the result for IJBC is :
|                                                                           |   1e-06 |   1e-05 |   0.0001 |   0.001 |     0.01    |      0.1      |
|:--------------------------------------------|--------:|-------:|------   -:|-------:|---------:|---------:|
| MS1MV2-ResNet100-Arcface/model,0_IJBC |          0 |         0 |             0 |          0 | 0.513882 | 0.557908 |

I print the mean of the score for  the positive pairs and the negative pairs, and they are 0.383 and 0.007 separately.
I think the reason for the poor result is the low score for positive pairs but I can't really find out what's the problem since the result for IJBB is totally right. Could you please help me? Thanks a lot!

**Comment by leondgarse** [comment]
I found it!
It's only the `read_template_pair_list` function, that `IJB_11.py` is using `pd.read_csv` instead of `np.loadtxt`.
I'm trying to fix this...

**Comment by pansanity666** [comment]
> I found it!
> It's only the `read_template_pair_list` function, that `IJB_11.py` is using `pd.read_csv` instead of `np.loadtxt`.
> I'm trying to fix this...

good job! it confused me for quite a few days! waiting for your good news!

**Comment by leondgarse** [comment]
@pansanity666 I made a [pull request here](https://github.com/deepinsight/insightface/pull/1364), and also the `IJBC` test results.

**Comment by pansanity666** [comment]
> @pansanity666 I made a [pull request here](https://github.com/deepinsight/insightface/pull/1364), and also the `IJBC` test results.

Thank you soooo much! the problem has been solved! 
And, I am also interested in the reason for the bug. What's the problem with np.loadtxt ? XD

**Comment by leondgarse** [comment]
I didn't dig deep, but it seems not as expected using `dtype=str` in `np.loadtxt`. The result seems like limited as `length<=5`.
```py
!tail /datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt -n 3
# 171707 183140 0
# 171707 182146 0
# 171707 185794 0

meta = np.loadtxt('/datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt', delimiter=' ', dtype=int)
print(meta[-3:])
# [[171707 183140      0]
#  [171707 182146      0]
#  [171707 185794      0]]

meta = np.loadtxt('/datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt', delimiter=' ', dtype=str)
print(meta[-3:])
# [['17170' '18314' '0']
#  ['17170' '18214' '0']
#  ['17170' '18579' '0']]
```
Also, `np.loadtxt` performs much slower comparing `pd.read_csv`.

**Comment by leondgarse** [comment]
I took some tests, and confused...
Load and print to see if the last line is right:
```py
def foo(pp):
    aa = np.loadtxt(pp, delimiter=' ', dtype=str)
    print(aa[-1], aa.dtype)
```
First test a part data from `ijbc_template_pair_label.txt`, cut a section out then run `loadtxt --> print`:
```sh
# OK
!head -n 7890641 /datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt | tail -n 50001 > goo
foo('goo')  # ['170001' '178303' '1'] <U6

# NOT OK
!head -n 7890641 /datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt | tail -n 50002 > goo
foo('goo')  # ['17000' '17830' '1'] <U5
```
But it's not because the file size:
```sh
# OK
!head -n 7890646 /datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt | tail -n 50006 > goo
foo('goo')  # ['170001' '178308' '1'] <U6

# NOT OK
!head -n 7890646 /datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt | tail -n 50007 > goo
foo('goo')  # ['17000' '17830' '1'] <U5
```
Pick that part out:
```sh
!head -n 7890641 /datasets/IJB_release/IJBC/meta/ijbc_template_pair_label.txt | tail -n 50002 > koo
```
Test using `head` and `tail` data:
```sh
# NOT OK
!head -n 25001 koo > goo && tail -n 25001 koo >> goo
foo('goo')  # ['17000' '17830' '1'] <U5

# OK
!head -n 25001 koo > goo && tail -n 25000 koo >> goo
foo('goo')  # ['170001' '178303' '1'] <U6

# OK
!head -n 50000 koo > goo && tail -n 1 koo >> goo
foo('goo')  # ['170001' '178303' '1'] <U6
```
Or even a larger file that contains all those data:
```sh
# OK
!head -n 30000 koo > goo && tail -n 20000 koo >> goo && head -n 25000 koo >> goo && tail -n 25000 koo >> goo
foo('goo')  # ['170001' '178303' '1'] <U6
```

**Comment by leondgarse** [comment]
OK, It's clarified here [loadtxt() changes numbers if integers are read as strings](https://github.com/numpy/numpy/issues/17277), and it's easy to reproduce and fix:
```py
aa = [[1, 1, 1]] * 50001
aa.append([12, 12, 12])
np.savetxt('foo', aa, fmt='%d')

bb = np.loadtxt('foo', delimiter=' ', dtype=str)
print(aa[-1], bb[-1], bb.dtype)
# [12, 12, 12] ['1' '1' '1'] <U1

cc = np.loadtxt('hoo', delimiter=' ', dtype='U2')
print(aa[-1], cc[-1], cc.dtype)
# [12, 12, 12] ['12' '12' '12'] <U2
```

**Comment by pansanity666** [comment]
> OK, It's clarified here [loadtxt() changes numbers if integers are read as strings](https://github.com/numpy/numpy/issues/17277), and it's easy to reproduce and fix:
> 
> ```python
> aa = [[1, 1, 1]] * 50001
> aa.append([12, 12, 12])
> np.savetxt('foo', aa, fmt='%d')
> 
> bb = np.loadtxt('foo', delimiter=' ', dtype=str)
> print(aa[-1], bb[-1], bb.dtype)
> # [12, 12, 12] ['1' '1' '1'] <U1
> 
> cc = np.loadtxt('foo', delimiter=' ', dtype='U2')
> print(aa[-1], cc[-1], cc.dtype)
> # [12, 12, 12] ['12' '12' '12'] <U2
> ```

Good job! Thank you very much!

**Comment by pansanity666** [comment]
Hi, I am encountered with another problem. I found that the provided calculation of 1:N evaluation is different from the definition of [DIR_FAR curve](http://www.cbsr.ia.ac.cn/users/scliao/papers/Liao-IJCB14-BLUFR.pdf) for open-set identification test. Do you know what metrics are the code calculating? And, what's more, do you know where to get the official code for DIR_FAR curve calculation? Thank you very much!

**Pull request merged**
