### PR TITLE
add simplifier in torch2onnx

### PR DESCRIPTION
**Pull request by 007gzs**

### CODE REVIEW

**Comment by nttstar** [comment]
@007gzs Have you tested if it works while the first input dim is 'None'?

**Comment by 007gzs** [comment]
刚才试过可以正常生成onnx，不过onnx文件还没测试，这个’None'之前就是这样的，我也不太知道原因


Jia Guo ***@***.***>于2021年5月19日 周三下午8:26写道：

**Comment by 007gzs** [comment]
刚才测试了下昨天生成的onnx，可以正常识别  https://pan.baidu.com/s/1Lp3H3oz8O6w1wC9S7CSL-w 提取码：face

**Comment by mnakhaeecourse** [comment]
> I just tested the onnx generated yesterday, and it can be recognized normally. https://pan.baidu.com/s/1Lp3H3oz8O6w1wC9S7CSL-w extraction code: face

I can't download it. I'd be grateful if you put it on dropbox or google drive

**Comment by 007gzs** [comment]
> > I just tested the onnx generated yesterday, and it can be recognized normally. https://pan.baidu.com/s/1Lp3H3oz8O6w1wC9S7CSL-w extraction code: face
> 
> I can't download it. I'd be grateful if you put it on dropbox or google drive
https://www.dropbox.com/sh/yhlrgfgolphqqt5/AADBiAFlVL8TYne-4L6_udCha

**Pull request merged**
